version: "3.9"

services:
  db:
    image: postgres:15
    container_name: league-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: league_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
 
  backend:
    build: ./backend
    container_name: league-backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/league_app
      RIOT_API_KEY: ${RIOT_API_KEY}   # set in .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: league-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
